production:
  solr:
    hostname: 45.55.74.230
    port: 8983
    log_level: DEBUG
    path: /solr/default
    # read_timeout: 2
    # open_timeout: 0.5
    solr_home: solr

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
